template_path: template.yaml

region: ca-central-1

parameters:
  DlqName: {{stack_group_config.dlq_name}}
  Role: !stack_output main/dev/base.yaml::FnRole
  TelegramBotToken: !aws ssm::get_parameter::'Name':'bot-token','WithDecryption':True::Parameter.Value::us-east-1
  TelegramChatId: !aws ssm::get_parameter::'Name':'/cfn-failures-to-telegram/chat-id'::Parameter.Value::us-east-1
  TopicName: cloudformation-stack-events
